// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Kcd0DNqVX3prVecUVTUjr4MYYQeYnDo',
    appId: '1:440668168222:web:ebb1519c38c69dd4d9ce0f',
    messagingSenderId: '440668168222',
    projectId: 'chatapp-b33a8',
    authDomain: 'chatapp-b33a8.firebaseapp.com',
    storageBucket: 'chatapp-b33a8.appspot.com',
    measurementId: 'G-ZNXX1VCS1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGMHemukj-qZ-aCUBc-NyOPQqQIt55T0',
    appId: '1:440668168222:android:7c590292e0446989d9ce0f',
    messagingSenderId: '440668168222',
    projectId: 'chatapp-b33a8',
    storageBucket: 'chatapp-b33a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtYMsSJh22hhWscwycrVbAkEr3QLQ6cqc',
    appId: '1:440668168222:ios:a72f4c7b5e43fb9cd9ce0f',
    messagingSenderId: '440668168222',
    projectId: 'chatapp-b33a8',
    storageBucket: 'chatapp-b33a8.appspot.com',
    iosBundleId: 'com.example.chatpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtYMsSJh22hhWscwycrVbAkEr3QLQ6cqc',
    appId: '1:440668168222:ios:a72f4c7b5e43fb9cd9ce0f',
    messagingSenderId: '440668168222',
    projectId: 'chatapp-b33a8',
    storageBucket: 'chatapp-b33a8.appspot.com',
    iosBundleId: 'com.example.chatpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Kcd0DNqVX3prVecUVTUjr4MYYQeYnDo',
    appId: '1:440668168222:web:7d426441a6146446d9ce0f',
    messagingSenderId: '440668168222',
    projectId: 'chatapp-b33a8',
    authDomain: 'chatapp-b33a8.firebaseapp.com',
    storageBucket: 'chatapp-b33a8.appspot.com',
    measurementId: 'G-2JSQCWX0XX',
  );
}
